### ISSUE TITLE
Reproducing results for other models

### ISSUE THREAD

**Issue by deepaksinghcv** [Vastlab/Elephant-of-object-detection#4]
Hello.
I notice that there is only 1 config file pertaining to Faster RCNN.
Could you provide the config files for the remaining models (RetinaNet, etc.,)
Any suggestions in this direction would be helpful.

**Comment by akshay-raj-dhamija** [comment]
Hello, The configs for RetinaNet and MaskRCNN have now been added along with pre-trained models as mentioned in the README. Please note the parameters for the configs are motivated from the original detectron repo. Currently, as the config names suggest these are the 1x training models, you may get better results with longer training times with the 3x training models similar to the ones available at https://github.com/facebookresearch/detectron2/tree/master/configs/COCO-Detection
